config/routes.rb
Rails.application.routes.draw do
get 'signup' => 'users#new', :as =>'signup'
get 'login' => 'sessions#new', :as =>'login'
get 'logout' => 'sessions#delete', :as => 'logout'

  resources :sessions
  resources :users
  resources :comments

  
  root 'translations#index'

  resources :translations do
    resources :gwords
  end
  resources :vwords
  resources :gwords do
    resources :comments
      end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vword.rb
class Vword < ApplicationRecord
  has_many :translations
  has_many :gwords, through: :translations

  validates :entry, presence: true
end

app/controllers/vwords_controller.rb
class VwordsController < ApplicationController
  before_action :set_vword, only: [:show, :edit, :update, :destroy]

  # GET /vwords
  # GET /vwords.json
  def index
    @vwords = Vword.all
  end

  # GET /vwords/1
  # GET /vwords/1.json
  def show
  end

  # GET /vwords/new
  def new
    @vword = Vword.new
  end

  # GET /vwords/1/edit
  def edit
  end

  # POST /vwords
  # POST /vwords.json
  def create
    @vword = Vword.new(vword_params)

    respond_to do |format|
      if @vword.save
        format.html { redirect_to @vword, notice: 'Das Wort wurde erfolgreich angelegt.' }
        format.json { render :show, status: :created, location: @vword }
      else
        format.html { render :new }
        format.json { render json: @vword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vwords/1
  # PATCH/PUT /vwords/1.json
  def update
    respond_to do |format|
      if @vword.update(vword_params)
        format.html { redirect_to @vword, notice: 'Das Wort wurde erfolgreich bearbeitet.' }
        format.json { render :show, status: :ok, location: @vword }
      else
        format.html { render :edit }
        format.json { render json: @vword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vwords/1
  # DELETE /vwords/1.json
  def destroy
    @vword.destroy
    respond_to do |format|
      format.html { redirect_to vwords_url, notice: 'Der Eintrag wurde erfolgreich gelöscht.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vword
      @vword = Vword.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vword_params
      params.require(:vword).permit(:entry)
    end
end

app/helpers/vwords_helper.rb
module VwordsHelper
end

app/views/vwords/_form.html.erb
<%= form_for(vword) do |f| %>
  <% if vword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vword.errors.count, "error") %> prohibited this vword from being saved:</h2>

      <ul>
      <% vword.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Wort %>
    <%= f.text_field :entry %>
  </div>

  <div class="actions">
    <%= f.submit :Fertig%>
  </div>
<% end %>

app/views/vwords/edit.html.erb
<h1>Wort bearbeiten</h1>

<%= render 'form', vword: @vword %>

<%= link_to 'Anzeigen', @vword %> |
<%= link_to 'Zurück', vwords_path %> |
<!-- <%= link_to 'Löschen', vwords_path %> -->
<%= link_to 'Löschen', @vword, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/vwords/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vietnamesische Wörter</h1>

<table>
  <thead>
    <tr>
      <th>Wort</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vwords.each do |vword| %>
      <tr>
        <td><%= link_to vword.entry, edit_vword_path(vword) %></td>
        <!-- <td><%= link_to 'Anzeigen', vword %></td> -->
        <!-- <td><%= link_to 'Bearbeiten', edit_vword_path(vword) %></td> -->
        <!-- <td><%= link_to 'Löschen', vword, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Neues Wort anlegen', new_vword_path %>

</p>
<table>
  <tr>
    <th>Navigation</th>
    <td> <%= link_to 'Wörterbuch', translations_path %> </td>
  </tr>
  <tr>
    <th></th>
    <td><%= link_to 'Deutsche Wörter', gwords_path %> </td>
  </tr>
</table>

app/views/vwords/new.html.erb
<h1>Neues Wort anlegen</h1>

<%= render 'form', vword: @vword %>

<%= link_to 'Zurück', vwords_path %>

app/views/vwords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wort</strong>
  <%= @vword.entry %>
</p>

<%= link_to 'Bearbeiten', edit_vword_path(@vword) %> |
<%= link_to 'Zurück', vwords_path %>