config/routes.rb
Rails.application.routes.draw do
get 'signup' => 'users#new', :as =>'signup'
get 'login' => 'sessions#new', :as =>'login'
get 'logout' => 'sessions#delete', :as => 'logout'

  resources :sessions
  resources :users
  resources :comments

  
  root 'translations#index'

  resources :translations do
    resources :gwords
  end
  resources :vwords
  resources :gwords do
    resources :comments
      end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/translation.rb
class Translation < ApplicationRecord
  belongs_to :gword
  belongs_to :vword
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_action :set_translation, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, only: [:show, :edit, :create]

  # GET /translations
  # GET /translations.json
  def index
    if params[:search].blank?
      # @gwords = Gword.where(["entry LIKE ?","%#{params[:search]}%"])
      @translations = Translation.all
      @gwords = Gword.all
      # @translations = Translation.joins("Left JOIN 'gwords' ON gwords.id = translations.gword_id").where(["gword.entry = ?", "%#{params[:search]}%"])
    else
      # @gwords = Gword.all
      # @gwords = @gwords.search(params[:search]
      @gwords = Gword.joins("LEFT JOIN Translations ON Translations.gword_id= gwords.id").where(["gwords.entry LIKE ?", "%#{params[:search]}%"])
    end
  end


  # GET /translations/1
  # GET /translations/1.json
  def show
    @translations = Translations.all
  end

  # GET /translations/new
  def new
    @translation = Translation.new
  end

  # GET /translations/1/edit
  def edit
  end

  # POST /translations
  # POST /translations.json
  def create
    @translation = Translation.new(translation_params)

    respond_to do |format|
      if @translation.save
        format.html { redirect_to @translation, notice: 'Der Eintrag wurde erfolgreich angelegt.' }
        format.json { render :show, status: :created, location: @translation }
      else
        format.html { render :new }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /translations/1
  # PATCH/PUT /translations/1.json
  def update
    respond_to do |format|
      if @translation.update(translation_params)
        format.html { redirect_to @translation, notice: 'Der Eintrag wurde erfolgreich bearbeitet.' }
        format.json { render :show, status: :ok, location: @translation }
      else
        format.html { render :edit }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translations/1
  # DELETE /translations/1.json
  def destroy
    @translation.destroy
    respond_to do |format|
      format.html { redirect_to translations_url, notice: 'Der Eintrag wurde erfolgreich gelöscht.' }
      format.json { head :no_content }
    end
  end

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_translation
      @translation = Translation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def translation_params
      params.require(:translation).permit(:explain, :like, :gword_id, :vword_id)
    end




  end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/translations/_form.html.erb
<%= form_for(translation) do |f| %>
  <% if translation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(translation.errors.count, "error") %> prohibited this translation from being saved:</h2>

      <ul>
      <% translation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Deutsch %>
    <%= f.text_field :gword_id %>
  </div>

  <div class="field">
    <%= f.label :Vietnamesisch %>
    <%= f.text_field :vword_id %>
  </div>

  <div class="field">
    <%= f.label :Beispielsatz %>
    <%= f.text_area :explain %>
  </div>

  <div class="field">
    <%= f.label :like %>
    <%= f.check_box :like %>
  </div>



  <div class="actions">
    <%= f.submit :Fertig %>
  </div>
<% end %>

app/views/translations/edit.html.erb
<h1>Übersetzung bearbeiten</h1>

<%= render 'form', translation: @translation %>

<%= link_to 'Anzeigen', @translation %> |
<%= link_to 'Zurück', translations_path %>

app/views/translations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wörterbuch: Deutsch-Vietnamesisch</h1>

<%= form_tag translations_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Suche" %>
<% end %>

</br>
<% if @translations %>
<table>
  <thead>
    <tr>
      <th>Deutsch</th>
      <th>Vietnamesisch</th>
      <th>Beispielsatz</th>
      <!-- <th>Like</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @translations.each do |translation| %>
      <tr>
        <td><%= link_to translation.gword.entry,   translation_gword_path(translation, translation.gword.id) %></td>
        <td><%= translation.vword.entry %></td>
        <td><%= translation.explain %></td>
        <!-- <td><%= translation.like %></td> -->
        <td><%= link_to 'Anzeigen', translation %></td>
        <!-- <td><%= link_to 'Bearbeiten', edit_translation_path(translation) %></td> -->
        <!-- <td><%= link_to 'Löschen', translation, method: :delete, data: { confirm: 'Bist du sicher?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>
</br>
<%= link_to 'Neue Übersetzung', new_translation_path %>
<% elsif @gwords.empty? %>
<h3> Kein Wort mit <i><%= params[:search]%></i> gefunden. </h3>
<%= link_to 'Zurück zum Wörterbuch', translations_path %>
<% else %>
<table>
  <thead>
    <tr>
      <th>Deutsch</th>
    </tr>
  </thead>

  <tbody>
      <%= @gwords.each do |g| %>
  <tr>
    <td> <%= g.entry %> </td>
  </tr>
  <% end %>
  </tbody>
</table>
</br>
<%= link_to 'Zurück zum Wörterbuch', translations_path %>

<% end %>

</p>
______________________________ </p>
<% if current_user %>
  Angemeldet als <b><%= current_user.name %></b>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= link_to 'Benutzeraccount anlegen', signup_path %> oder
  <%= link_to 'Anmelden', login_path %> </td>
<% end %>
<p>
</p>
<table>
  <tr>
    <th>Navigation</th>
    <td> <%= link_to 'Deutsche Wörter', gwords_path %> </td>
  </tr>
  <tr>
    <th></th>
    <td><%= link_to 'Vietnamesische Wörter', vwords_path %> </td>
  </tr>
</table>

app/views/translations/new.html.erb
<h1>Neue Übersetzung</h1>

<%= render 'form', translation: @translation %>

<%= link_to 'Zurück', translations_path %>

app/views/translations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Deutsch</strong>
  <%= @translation.gword.entry %>
</p>

<p>
  <strong>Vietnamesisch</strong>
  <%= @translation.vword.entry %>
</p>

<p>
  <strong>Beispielsatz:</strong>
  <%= @translation.explain %>
</p>

<p>
  <strong>Like:</strong>
  <%= @translation.like %>
</p>
<%= link_to 'Bearbeiten', edit_translation_path(@translation) %> |
<%= link_to 'Zurück', translations_path %>