config/routes.rb
Rails.application.routes.draw do
get 'signup' => 'users#new', :as =>'signup'
get 'login' => 'sessions#new', :as =>'login'
get 'logout' => 'sessions#delete', :as => 'logout'

  resources :sessions
  resources :users
  resources :comments

  
  root 'translations#index'

  resources :translations do
    resources :gwords
  end
  resources :vwords
  resources :gwords do
    resources :comments
      end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gword.rb
class Gword < ApplicationRecord
  has_many :translations
  has_many :vwords, through: :translations
  has_many :comments

  validates :entry, presence: true
end

app/controllers/gwords_controller.rb
class GwordsController < ApplicationController
  before_action :set_gword, only: [:show, :edit, :update, :destroy]


  # GET /gwords
  # GET /gwords.json
  def index
    @gwords = Gword.all
  end

  # GET /gwords/1
  # GET /gwords/1.json
  def show
    @comments = @gword.comments.all
    @comment = @gword.comments.build
  end

  # GET /gwords/new
  def new
    @gword = Gword.new
  end

  # GET /gwords/new2
  def new2
    @gword = Gword.new
  end

  # GET /gwords/1/edit
  def edit
  end

  # POST /gwords
  # POST /gwords.json
  def create
    @gword = Gword.new(gword_params)

    respond_to do |format|
      if @gword.save
        format.html { redirect_to @gword, notice: 'Der Eintrag wurde erfolgreich angelegt.' }
        format.json { render :show, status: :created, location: @gword }
      else
        format.html { render :new }
        format.json { render json: @gword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gwords/1
  # PATCH/PUT /gwords/1.json
  def update
    respond_to do |format|
      if @gword.update(gword_params)
        format.html { redirect_to @gword, notice: 'Der Eintrag wurde erfolgreich bearbeitet.' }
        format.json { render :show, status: :ok, location: @gword }
      else
        format.html { render :edit }
        format.json { render json: @gword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gwords/1
  # DELETE /gwords/1.json
  def destroy
    @gword.destroy
    respond_to do |format|
      format.html { redirect_to gwords_url, notice: 'Der Eintrag wurde erfolgreich gelöscht.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gword
      @gword = Gword.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gword_params
      params.require(:gword).permit(:entry)
    end
end

app/helpers/gwords_helper.rb
module GwordsHelper
end

app/views/gwords/_form.html.erb
<%= form_for(gword) do |f| %>
  <% if gword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gword.errors.count, "error") %> prohibited this gword from being saved:</h2>

      <ul>
      <% gword.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :Wort %>
    <%= f.text_field :entry %>
  </div>

  <div class="actions">
    <%= f.submit :Fertig%>
  </div>
<% end %>

app/views/gwords/edit.html.erb
<h1>Wort bearbeiten</h1>

<%= render 'form', gword: @gword %>

<%= link_to 'Anzeigen', @gword %> |
<%= link_to 'Zurück', gwords_path %>

app/views/gwords/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Deutsche Wörter</h1>

<!-- <%= form_tag gwords_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Suche" %>
<% end %> -->

<table>
  <thead>
    <tr>
      <th>Wort</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>    <% @gwords.each do |gword| %>      <tr>        <td><%= link_to gword.entry, edit_gword_path(gword) %></td>        <td><%= link_to 'Definition', gword %></td>        <!-- <td><%= link_to 'Bearbeiten', edit_gword_path(gword) %></td> -->        <!-- <td><%= link_to 'Löschen', gword, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->      </tr>    <% end %>  </tbody>
</table>



<br>
<%= link_to 'Neues Wort anlegen', new_gword_path %>

</p>
<table>
  <tr>
    <th>Navigation</th>
    <td> <%= link_to 'Wörterbuch', translations_path %> </td>
  </tr>
  <tr>
    <th></th>
    <td><%= link_to 'Vietnamesische Wörter', vwords_path %> </td>
  </tr>
</table>

app/views/gwords/new.html.erb
<h1>Neues Wort</h1>

<%= render 'form', gword: @gword %>

<%= link_to 'Zurück', gwords_path %>

app/views/gwords/new2.html.erb
<h1>Neues Wort</h1>

<form role="form">
  <div class="form-group">
    <label for="username">Username</label>
    <input type="text" id="username" name="username" class="form-control" />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" id="password" name="password" class="form-control" />
  </div>

  <input type="submit" value="Login" />
  <input type="button" value="Cancel" />
</form>

app/views/gwords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Entry:</strong>
  <%= @gword.entry %>
</p>

<h3>Kommentare</h3>
<table>
  <% @comments.each do |comment| %>
    <tr>
      <th><%= comment.commenter %> sagt</th>
      <td><%= comment.body %> <tab> <i>am <%= comment.created_at %></i> </td>
    </tr>
    <%end%>
</table>

<h2>Kommentare hinzufügen</h2>
<%= form_for @comment do |f| %>
<p>
  <%= f.label :Name %></br>
  <%= f.text_field :commenter %>
</p>

<p>
<%= f.label :Kommentar %></br>
<%= f.text_field :body %>
</p>

<%= f.hidden_field :gword_id %>

<!-- <p>
  <%= f.label :gword_id %></br>
  <%= f.text_field :gword_id %>
</p> -->

<p>
  <%= f.submit :Kommentieren%>
</p>
<% end %>


<!-- <%= link_to 'Bearbeiten', edit_gword_path(@gword) %> | -->
<%= link_to 'Zurück', gwords_path %>